- src/fmu/ensemble/ensemble.py
- src/fmu/ensemble/realization.py
> Avoid recurring into restart unsmry files

- src/fmu/ensemble/realization.py
- tests/test_realization.py
> Support FMU-independent realizations

- docs/concepts.rst
- src/fmu/ensemble/ensemble.py
- src/fmu/ensemble/ensembleset.py
- src/fmu/ensemble/realization.py
- tests/test_ensemble.py
> Noautodiscovery

- src/fmu/ensemble/ensemble.py
- src/fmu/ensemble/ensembleset.py
- src/fmu/ensemble/realization.py
- src/fmu/ensemble/virtualensemble.py
- src/fmu/ensemble/virtualrealization.py
> Change logger.warn to logger.warning

- .travis.yml
- Makefile
- README.rst
> Automatic documentation deploy

- docs/usage.rst
- src/fmu/ensemble/etc.py
Also list ERROR as a valid logging level, some modules log to there
> Change default log level to WARNING

- requirements.txt
- src/fmu/ensemble/ensemble.py
- src/fmu/ensemble/virtualensemble.py
- tests/test_ensemble.py
- tests/test_ensemblecombination.py
> Filter away non-numerical columns before aggregation

- .pylintrc
- src/fmu/ensemble/ensembleset.py
- src/fmu/ensemble/realization.py
- tests/test_ensemble.py
- tests/test_realization.py
- tests/test_virtualrealization.py
> Codequality

- docs/advancedusage.rst
- src/fmu/ensemble/observations.py
- src/fmu/ensemble/realization.py
- tests/test_observations.py
- tests/test_realization.py
Partially solves #1. Fully resolves #23, fully resolves #50, fully resolves #51.
> Observation and mismatch handling improvements

- src/fmu/ensemble/ensemble.py
- src/fmu/ensemble/realization.py
- tests/test_realization.py
> find_files() added features, file components and associated yaml files.

- docs/advancedusage.rst
- src/fmu/ensemble/observations.py
- tests/test_observations.py
> Support dates in time_index in smryh

- src/fmu/ensemble/virtualensemble.py
- tests/test_batch.py
- tests/test_ensemble.py
- tests/test_virtualensemble.py
Solves #85 
(and refactors batch testing)
> Manifestbug

- src/fmu/ensemble/ensemblecombination.py
- src/fmu/ensemble/observations.py
- src/fmu/ensemble/realizationcombination.py
- src/fmu/ensemble/virtualensemble.py
- src/fmu/ensemble/virtualrealization.py
- tests/test_ensemblecombination.py
Fix bug related to finding representative realizations for delta profiles.
> Observations.load_smry() on EnsembleCombinations

- .travis.yml
- README.rst
- requirements.txt
> Install libecl from pypi, and extend CI to include Python 3.7-3.8

- src/fmu/ensemble/__init__.py
- src/fmu/ensemble/_theversion.py
- src/fmu/ensemble/ensemble.py
- src/fmu/ensemble/ensemblecombination.py
- src/fmu/ensemble/ensembleset.py
- src/fmu/ensemble/etc.py
- src/fmu/ensemble/observations.py
- src/fmu/ensemble/realization.py
- src/fmu/ensemble/realizationcombination.py
- src/fmu/ensemble/virtualensemble.py
- src/fmu/ensemble/virtualrealization.py
- tests/test_batch.py
- tests/test_ecl2df.py
- tests/test_ensemble.py
- tests/test_ensemble_agg.py
- tests/test_ensemble_eclfail.py
- tests/test_ensemblecombination.py
- tests/test_ensembleset.py
- tests/test_observations.py
- tests/test_realization.py
- tests/test_realizationcombination.py
- tests/test_virtualensemble.py
- tests/test_virtualrealization.py
There are only a few accepted pylint exceptions added. 
* Allowing import to happen down in the code to avoid cycling import issues
* Allowing access to private functions in test code
* Allowing duplicate code in test code
* Allowing pointless statements and missing parameters in test code
> Linting, getting code rating A again

- src/fmu/ensemble/ensemble.py
- src/fmu/ensemble/ensemblecombination.py
- src/fmu/ensemble/realization.py
- src/fmu/ensemble/realizationcombination.py
- src/fmu/ensemble/virtualensemble.py
- src/fmu/ensemble/virtualrealization.py
- tests/test_ensemblecombination.py
- tests/test_realizationcombination.py
> Let virtual ens/real be combinable

- src/fmu/__init__.py
- src/fmu/ensemble/ensemble.py
- src/fmu/ensemble/ensemblecombination.py
- src/fmu/ensemble/ensembleset.py
- src/fmu/ensemble/observations.py
- src/fmu/ensemble/realizationcombination.py
- src/fmu/ensemble/virtualensemble.py
- src/fmu/ensemble/virtualrealization.py
- tests/test_batch.py
- tests/test_ensemble.py
- tests/test_ensemble_agg.py
- tests/test_ensemblecombination.py
- tests/test_ensembleset.py
- tests/test_observations.py
- tests/test_virtualensemble.py
- tests/test_virtualrealization.py
Some leftover linting
Remaining subprocess warnings willl be removed when versioneer is purged in #108
> Leftover linting

- .travis.yml
- requirements.txt
- setup.py
- src/fmu/ensemble/virtualensemble.py
- tests/test_virtualensemble.py
pyarrow has been problematic to install in some instances
Resolves #102
> Make pyarrow optional dependency

- src/fmu/ensemble/realization.py
> Resolve DeprecationWarning on MutableMapping

- src/fmu/ensemble/ensemble.py
- src/fmu/ensemble/ensemblecombination.py
- src/fmu/ensemble/realizationcombination.py
- src/fmu/ensemble/virtualensemble.py
- tests/test_ensemblecombination.py
- tests/test_realizationcombination.py
> Extend combinations API

- src/fmu/ensemble/observations.py
- tests/test_observations.py
Instead of trying to guess a filename.
Resolves #73
> Let observations use virtreal.get_smry()

- src/fmu/ensemble/ensemble.py
- src/fmu/ensemble/ensemblecombination.py
- src/fmu/ensemble/realization.py
- src/fmu/ensemble/realizationcombination.py
- src/fmu/ensemble/virtualensemble.py
- src/fmu/ensemble/virtualrealization.py
- tests/test_batch.py
- tests/test_ecl2df.py
- tests/test_ensemble.py
- tests/test_ensemblecombination.py
- tests/test_realization.py
- tests/test_realizationcombination.py
- tests/test_virtualensemble.py
- tests/test_virtualrealization.py
> Get summary metadata

- src/fmu/ensemble/ensemble.py
- src/fmu/ensemble/ensemblecombination.py
- src/fmu/ensemble/ensembleset.py
- src/fmu/ensemble/observations.py
- src/fmu/ensemble/realization.py
- src/fmu/ensemble/realizationcombination.py
- src/fmu/ensemble/virtualensemble.py
- src/fmu/ensemble/virtualrealization.py
- tests/test_ensemble.py
- tests/test_ensemblecombination.py
- tests/test_ensembleset.py
- tests/test_realization.py
- tests/test_realizationcombination.py
- tests/test_virtualensemble.py
- tests/test_virtualrealization.py
> Direct merge support in get_df()

- .gitignore
- tests/test_ensemble.py
- tests/test_ensemble_agg.py
- tests/test_ensembleset.py
- tests/test_observations.py
- tests/test_realization.py
- tests/test_virtualensemble.py
- tests/test_virtualrealization.py
> Use tmpdir fixture in tests, allow parallel tests

- src/fmu/ensemble/realization.py
> Muteautodisc

- tests/test_virtualensemble.py
Fix test-code bug that occurs in #119
> Fine-tune tests when pyarrow is not included

- src/fmu/ensemble/virtualensemble.py
Needed for dataframes that has been on disk
> Convert nan to None for get_smry_meta

- docs/_templates/layout.html
Kudos @HansKallekleiv in fmu-tools.
> Make version visible in sphinx

- src/fmu/ensemble/ensemble.py
- src/fmu/ensemble/realization.py
10 recommendations  not fixed, relating to code duplications.
> Fix lgtm issues

- src/fmu/ensemble/virtualrealization.py
> Better error message from virtualrealization.get_smry()

- .github/workflows/fmu-ensemble.yml
- setup.py
Reverts equinor/fmu-ensemble#137
> Revert "Rm libecl from requirements in order to solve other problems"

- .github/workflows/fmu-ensemble.yml
- setup.py
Revert the revert of remove libecl reqs..
> Remove libecl requirements, whenever it is custom installed and not pip

- src/fmu/ensemble/virtualensemble.py
> Removed logging level=INFO in virtual_ensemble.py

- tests/test_realization.py
Prove and verify that spaces in values are supported, as long as they are quoted.
> Spaces in values in parameters.txt

- .github/workflows/fmu-ensemble.yml
- src/fmu/ensemble/virtualensemble.py
- src/fmu/ensemble/virtualrealization.py
Also fix minor logging string bug
> Make compatible with Pandas 1.1.0

- tests/test_ensemble_agg.py
> removed outdated comment

- src/fmu/ensemble/ensemble.py
- src/fmu/ensemble/realization.py
- src/fmu/ensemble/virtualensemble.py
> Fix unclosed file

- src/fmu/ensemble/ensemble.py
- src/fmu/ensemble/ensemblecombination.py
- src/fmu/ensemble/ensembleset.py
- tests/test_ensemble.py
- tests/test_ensembleset.py
> Catch KeyError when parameters is requested as class property

- .github/workflows/fmu-ensemble.yml
- setup.py
`2020.12` komodo to use `ecl`from PyPI.
> Use ecl from PyPI

- src/fmu/ensemble/ensemble.py
...and change to `logger.info` instead.
> Remove print during grid reading

- .github/workflows/fmu-ensemble.yml
- setup.py
0.24.2 is no longer relevant to test.
> Skip testing old Pandas

- src/fmu/ensemble/ensemble.py
- tests/test_etc.py
The multiple imports in the test code masked the import error in previous code.
> Fix bug in bugfix, imports not properly done

- src/fmu/ensemble/ensembleset.py
- src/fmu/ensemble/realization.py
- src/fmu/ensemble/virtualrealization.py
Solve properly when dropping Python 3.6
Solves #217 , similarly to #215
> Mute more FutureWarnings.

- src/fmu/ensemble/observations.py
- tests/test_observations.py
> Forward label from observations dataframes to mismatch dfs

- setup.py
- src/fmu/ensemble/realization.py
Needed to use pandas 1.5.0
Resolves: #223
> Add empty col to data frame

- .github/workflows/fmu-ensemble.yml
- setup.py
> Unpin setuptools_scm

- src/fmu/ensemble/realization.py
> Postpone import of deprecated ecl2df
